[package]
name = "a2ltool"
version = "1.3.0"
authors = ["Daniel Thaler <daniel@dthaler.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a2lfile = "1.3.1"
object = "~0.28"
gimli = { version = "~0.26", features = ["read"] }
memmap = "~0.7"
clap = "~4.0"
cpp_demangle = "0.3.5"
regex = "1"

[profile.release]
lto = "fat"
