[package]
name = "a2ltool"
version = "1.6.0"
authors = ["Daniel Thaler <daniel@dthaler.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a2lfile = "2.0.0"
object = { version = "~0.32", default_features = false, features = ["read"] }
gimli = { version = "~0.28", default_features = false, features = ["read"] }
memmap = "~0.7"
clap = { version = "~4.0", features = ["wrap_help"]}
cpp_demangle = "0.4.3"
regex = "1"
indexmap = "2.2.0"
fxhash = "0.2.1"

[profile.release]
panic = "abort"
strip = "debuginfo"
lto = "fat"
