[package]
name = "a2ltool"
version = "1.4.4"
authors = ["Daniel Thaler <daniel@dthaler.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a2lfile = "1.4.0"
object = "~0.32"
gimli = { version = "~0.28", features = ["read"] }
memmap = "~0.7"
clap = { version = "~4.4", features = ["wrap_help"]}
cpp_demangle = "0.4.3"
regex = "1"

[profile.release]
lto = "fat"
