[package]
name = "a2ltool"
version = "0.8.0"
authors = ["Daniel Thaler <daniel@dthaler.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.a2lfile]
version = "0.8.0"
# path = "../a2lfile"

[dependencies]
object = "0.23"
gimli = "0.23"
memmap = "0.7"
clap = "~2.33.0"

[build-dependencies]
vergen = { version = "5", default-features = false, features = ["build", "git"] }
