[package]
name = "a2ltool"
version = "0.9.2"
authors = ["Daniel Thaler <daniel@dthaler.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a2lfile = "0.9.1"
object = "~0.26"
gimli = "~0.25"
memmap = "~0.7"
clap = "~2.33.0"
cpp_demangle = "0.3.3"
